const actionTypes = {
    SET_IMAGES: 'SET_IMAGES',
    SET_SELECTED_LANG: 'SET_SELECTED_LANG',
    SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY',
    SET_LIST_VIEW: 'SET_LIST_VIEW'
}
export default actionTypes;